# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-kilted-rosidl-runtime-cpp
  version: 4.9.5
source:
  git: https://github.com/ros2-gbp/rosidl-release.git
  tag: release/kilted/rosidl_runtime_cpp/4.9.5-1
  target_directory: ros-kilted-rosidl-runtime-cpp/src/work
  patches:
    - patch/ros-kilted-rosidl-runtime-cpp.osx.patch

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 13
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - numpy
    - pip
    - python
    - ros-kilted-ament-cmake
    - ros-kilted-ament-cmake-gtest
    - ros-kilted-ament-lint-auto
    - ros-kilted-ament-lint-common
    - ros-kilted-performance-test-fixture
    - ros-kilted-ros-environment
    - ros-kilted-ros-workspace
    - ros-kilted-rosidl-runtime-c
    - ros2-distro-mutex 0.11.* kilted_*
  run:
    - python
    - ros-kilted-ament-cmake
    - ros-kilted-ros-workspace
    - ros-kilted-rosidl-runtime-c
    - ros2-distro-mutex 0.11.* kilted_*
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
