# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-kilted-autoware-mission-planner
  version: 1.4.0
source:
  git: https://github.com/ros2-gbp/autoware_core-release.git
  tag: release/humble/autoware_mission_planner/1.4.0-1
  target_directory: ros-kilted-autoware-mission-planner/src/work

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 12
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - numpy
    - pip
    - python
    - ros-kilted-ament-cmake-auto
    - ros-kilted-ament-cmake-ros
    - ros-kilted-ament-lint-auto
    - ros-kilted-autoware-adapi-v1-msgs
    - ros-kilted-autoware-cmake
    - ros-kilted-autoware-component-interface-specs
    - ros-kilted-autoware-lanelet2-extension
    - ros-kilted-autoware-lint-common
    - ros-kilted-autoware-map-msgs
    - ros-kilted-autoware-motion-utils
    - ros-kilted-autoware-planning-msgs
    - ros-kilted-autoware-route-handler
    - ros-kilted-autoware-test-utils
    - ros-kilted-autoware-utils-geometry
    - ros-kilted-autoware-utils-logging
    - ros-kilted-autoware-utils-math
    - ros-kilted-autoware-utils-system
    - ros-kilted-autoware-utils-visualization
    - ros-kilted-autoware-vehicle-info-utils
    - ros-kilted-geometry-msgs
    - ros-kilted-pluginlib
    - ros-kilted-rclcpp
    - ros-kilted-rclcpp-components
    - ros-kilted-ros-environment
    - ros-kilted-ros-workspace
    - ros-kilted-tf2-geometry-msgs
    - ros-kilted-tf2-ros
    - ros2-distro-mutex 0.11.* kilted_*
  run:
    - python
    - ros-kilted-autoware-adapi-v1-msgs
    - ros-kilted-autoware-component-interface-specs
    - ros-kilted-autoware-lanelet2-extension
    - ros-kilted-autoware-map-msgs
    - ros-kilted-autoware-motion-utils
    - ros-kilted-autoware-planning-msgs
    - ros-kilted-autoware-route-handler
    - ros-kilted-autoware-utils-geometry
    - ros-kilted-autoware-utils-logging
    - ros-kilted-autoware-utils-math
    - ros-kilted-autoware-utils-system
    - ros-kilted-autoware-utils-visualization
    - ros-kilted-autoware-vehicle-info-utils
    - ros-kilted-geometry-msgs
    - ros-kilted-pluginlib
    - ros-kilted-rclcpp
    - ros-kilted-rclcpp-components
    - ros-kilted-ros-workspace
    - ros-kilted-tf2-geometry-msgs
    - ros-kilted-tf2-ros
    - ros2-distro-mutex 0.11.* kilted_*
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
