# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-kilted-controller-manager
  version: 5.11.3
source:
  git: https://github.com/ros2-gbp/ros2_control-release.git
  tag: release/kilted/controller_manager/5.11.3-1
  target_directory: ros-kilted-controller-manager/src/work

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 15
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  license: Apache-2.0
  summary: The main runnable entrypoint of ros2_control and home of controller management and resource management.
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - coverage
    - fmt
    - numpy
    - pip
    - python
    - ros-kilted-ament-cmake
    - ros-kilted-ament-cmake-gen-version-h
    - ros-kilted-ament-cmake-gmock
    - ros-kilted-ament-cmake-pytest
    - ros-kilted-ament-cmake-python
    - ros-kilted-backward-ros
    - ros-kilted-controller-interface
    - ros-kilted-controller-manager-msgs
    - ros-kilted-diagnostic-updater
    - ros-kilted-example-interfaces
    - ros-kilted-generate-parameter-library
    - ros-kilted-hardware-interface
    - ros-kilted-hardware-interface-testing
    - ros-kilted-launch-testing
    - ros-kilted-libstatistics-collector
    - ros-kilted-lifecycle-msgs
    - ros-kilted-pluginlib
    - ros-kilted-rclcpp
    - ros-kilted-realtime-tools
    - ros-kilted-robot-state-publisher
    - ros-kilted-ros-environment
    - ros-kilted-ros-workspace
    - ros-kilted-ros2-control-cmake
    - ros-kilted-ros2-control-test-assets
    - ros-kilted-ros2pkg
    - ros-kilted-std-msgs
    - ros2-distro-mutex 0.13.* kilted_*
  run:
    - fmt
    - python
    - pyyaml
    - ros-kilted-backward-ros
    - ros-kilted-controller-interface
    - ros-kilted-controller-manager-msgs
    - ros-kilted-diagnostic-updater
    - ros-kilted-generate-parameter-library
    - ros-kilted-hardware-interface
    - ros-kilted-launch
    - ros-kilted-launch-ros
    - ros-kilted-launch-testing-ros
    - ros-kilted-libstatistics-collector
    - ros-kilted-lifecycle-msgs
    - ros-kilted-pluginlib
    - ros-kilted-rcl-interfaces
    - ros-kilted-rclcpp
    - ros-kilted-rclpy
    - ros-kilted-realtime-tools
    - ros-kilted-ros-workspace
    - ros-kilted-ros2param
    - ros-kilted-sensor-msgs
    - ros-kilted-std-msgs
    - ros2-distro-mutex 0.13.* kilted_*
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
