jobs:
  stage_0_job_0:
    name: autoware-localization-msgs autoware-trajectory autoware-downsample-filters
      autoware-simple-pure-pursuit
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs: []
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-kilted-autoware-localization-msgs ros-kilted-autoware-trajectory
        ros-kilted-autoware-downsample-filters ros-kilted-autoware-simple-pure-pursuit
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-kilted-autoware-localization-msgs ros-kilted-autoware-trajectory
          ros-kilted-autoware-downsample-filters ros-kilted-autoware-simple-pure-pursuit
        BUILD_TARGET: ''
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_1_job_1:
    name: autoware-component-interface-specs autoware-core-control autoware-pose-initializer
      autoware-core-localization
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_0_job_0
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-kilted-autoware-component-interface-specs ros-kilted-autoware-core-control
        ros-kilted-autoware-pose-initializer ros-kilted-autoware-core-localization
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-kilted-autoware-component-interface-specs ros-kilted-autoware-core-control
          ros-kilted-autoware-pose-initializer ros-kilted-autoware-core-localization
        BUILD_TARGET: ''
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
name: build_unix
on:
  push:
    branches:
    - buildbranch_linux
