on:
  pull_request:
  workflow_dispatch:

env:
  ROS_VERSION: 2

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux-64
          - os: ubuntu-24.04-arm
            platform: linux-aarch64
          - os: macos-13
            platform: osx-64
          - os: macos-14
            platform: osx-arm64
          - os: windows-2022
            platform: win-64

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - uses: prefix-dev/setup-pixi@v0.8.10
      with:
        pixi-version: v0.44.0
        frozen: true

    # Workaround for https://github.com/RoboStack/ros-humble/pull/141#issuecomment-1941919816
    - name: Clean up PATH
      if: contains(matrix.os, 'windows')
      uses: egor-tensin/cleanup-path@v4
      with:
        # cygpath in C:\Program Files\Git\usr\bin is used by install micromamba
        # git in C:\Program Files\Git\bin is used by pip install git+
        dirs: 'C:\Program Files\Git\usr\bin;C:\Program Files\Git\bin;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin'

    # For some reason, the Strawberry perl's pkg-config is found
    # instead of the conda's one, so let's delete the /c/Strawberry directory
    # Furthermore, we also need to remove an older SDK that is used and can result in compilation problems
    - name: Debug pkg-config problem
      if: contains(matrix.os, 'windows')
      shell: bash -l {0}
      run: |
        rm -rf /c/Strawberry
        rm -rf "/c/Program Files (x86)/Windows Kits/10/Include/10.0.17763.0/"

    # Regression for https://github.com/RoboStack/ros-jazzy/issues/44
    - name: Check that anaconda-client command works fine
      shell: bash -l {0}
      run: |
        pixi run anaconda --version

    - name: Long paths workarounds for win-64
      shell: bash -l {0}
      if: matrix.platform == 'win-64'
      run: |
        # Workaround for problem related to long paths
        echo "CONDA_BLD_PATH=C:\\bld\\" >> $GITHUB_ENV
        mkdir /c/bld

    - name: Generate recipes
      shell: bash -l {0}
      run: |
        mkdir -p recipes
        pixi run -v vinca --platform ${{ matrix.platform }} -m -n

    - name: Check patches
      shell: bash -l {0}
      run: |
        pixi run python check_patches_clean_apply.py

    - name: Build recipes
      shell: bash -l {0}
      run: |
        pixi run rattler-build build --recipe-dir recipes --target-platform ${{ matrix.platform }} -m ./conda_build_config.yaml -c robostack-kilted -c conda-forge --skip-existing
